"""
Report Service - Generate PDF drug discovery reports with ReportLab.
"""

from __future__ import annotations

import io
import logging
import html
from types import SimpleNamespace
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List
from uuid import UUID

from app.models.target_context import TargetContext

try:
    from rdkit import Chem
    from rdkit.Chem import Draw

    RDKIT_AVAILABLE = True
except ImportError:
    Chem = None
    Draw = None
    RDKIT_AVAILABLE = False

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.platypus import Image, KeepTogether, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

logger = logging.getLogger(__name__)

# FIXED
STANDARD_DISCLAIMER = (
    "All results are computational predictions generated by MolGenix. "
    "Docking scores, ADMET predictions, and druggability assessments require experimental validation before drawing "
    "biological conclusions. This report does not constitute clinical or therapeutic advice."
)


class ReportService:
    """Generate and persist PDF reports for a target and its molecules."""

    REPORT_STORAGE_DIR = Path("/app/reports")

    REQUIRED_ADMET_KEYS = {
        "bbbp_score",
        "hepatotoxicity_score",
        "herg_risk",
        "bioavailability_score",
        "solubility_score",
        "clearance_score",
        "cyp3a4_liability",
        "model_source",
    }

    @staticmethod
    def _styles():
        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle(name="MolTitle", fontSize=22, leading=28, spaceAfter=12))
        styles.add(ParagraphStyle(name="MolSubtitle", fontSize=13, leading=17, spaceAfter=8, textColor=colors.HexColor("#334155")))
        styles.add(ParagraphStyle(name="MolHeading", fontSize=17, leading=21, spaceAfter=10, textColor=colors.HexColor("#0f172a")))
        styles.add(ParagraphStyle(name="MolBody", fontSize=10, leading=14, spaceAfter=8, textColor=colors.HexColor("#111827")))
        styles.add(ParagraphStyle(name="MolSmall", fontSize=9, leading=12, spaceAfter=6, textColor=colors.HexColor("#475569")))
        styles.add(ParagraphStyle(name="MolLabel", fontSize=9, leading=11, spaceAfter=4, textColor=colors.HexColor("#64748b")))
        styles.add(ParagraphStyle(name="MolTable", fontSize=8.5, leading=10.5, spaceAfter=0, textColor=colors.HexColor("#111827")))
        return styles

    @staticmethod
    def _traffic_color(value: str) -> colors.Color:
        mapping = {
            "green": colors.HexColor("#1b8a3b"),
            "yellow": colors.HexColor("#c99700"),
            "red": colors.HexColor("#c0392b"),
            "unknown": colors.HexColor("#6b7280"),
        }
        return mapping.get(str(value).lower(), colors.HexColor("#6b7280"))

    @staticmethod
    def _molecule_report_name(index: int, molecule: Any) -> str:
        if getattr(molecule, "is_optimized", False):
            return f"MGX-OPT-{index:02d}"
        return f"MGX-{index:03d}"

    @staticmethod
    def _molecule_descriptors(molecule: Any) -> Dict[str, Any]:
        admet = molecule.admet_scores if isinstance(molecule.admet_scores, dict) else {}
        return {
            "molecular_weight": admet.get("molecular_weight", "N/A"),
            "logp": admet.get("logp", "N/A"),
            "hbd": admet.get("hbd", "N/A"),
            "hba": admet.get("hba", "N/A"),
        }

    @staticmethod
    def _format_value(value: Any, digits: int = 2) -> str:
        if value in (None, "", "N/A"):
            return "N/A"
        if isinstance(value, (int, float)):
            return f"{value:.{digits}f}"
        return str(value)

    @staticmethod
    def _has_complete_admet(admet_scores: Dict[str, Any]) -> bool:
        if not isinstance(admet_scores, dict):
            return False
        return all(key in admet_scores for key in ReportService.REQUIRED_ADMET_KEYS)

    @staticmethod
    async def _ensure_molecule_annotations(target: Any, molecules: List[Any], db: Any) -> List[Any]:
        """Backfill ADMET and provenance fields for report rendering."""
        from app.models.molecule import Molecule
        from app.services.admet_service import ADMETService

        missing_admet_ids = [
            str(molecule.id)
            for molecule in molecules
            if not ReportService._has_complete_admet(molecule.admet_scores or {})
        ]
        if missing_admet_ids:
            await ADMETService.score_molecules(
                ReportService._coerce_target_context(target),
                [molecule for molecule in molecules if str(molecule.id) in missing_admet_ids],
                db,
            )

        refreshed: List[Any] = []
        for molecule in molecules:
            refreshed_molecule = db.query(Molecule).filter(Molecule.id == molecule.id).first() or molecule
            metadata = dict(refreshed_molecule.admet_scores or {})
            docking_meta = metadata.get("_docking")

            if refreshed_molecule.docking_score is not None and not isinstance(docking_meta, dict):
                metadata["_docking"] = {
                    "method": "legacy_stored_score",
                    "is_mock": False,
                    "fallback_reason": None,
                    "pdb_filename": "unknown",
                }
            elif refreshed_molecule.docking_score is None and not isinstance(docking_meta, dict):
                metadata["_docking"] = {
                    "method": "not_run",
                    "is_mock": False,
                    "fallback_reason": "not_run",
                    "pdb_filename": "N/A",
                }

            if metadata != (refreshed_molecule.admet_scores or {}):
                refreshed_molecule.admet_scores = metadata
                db.add(refreshed_molecule)

            refreshed.append(refreshed_molecule)

        if missing_admet_ids or any((molecule.admet_scores or {}).get("_docking") for molecule in refreshed):
            db.commit()
            for molecule in refreshed:
                db.refresh(molecule)

        return refreshed

    @staticmethod
    def build_target_description(tc: TargetContext) -> str:
        lines = []
        lines.append(f"{tc.protein_name} ({tc.gene_symbol}) is associated with {tc.disease}.")
        if tc.target_class and tc.target_class not in {"unknown", "other"}:
            lines.append(f"Target class: {tc.target_class}.")
        if tc.function and tc.function != "N/A":
            sentences = tc.function.split(". ")[:2]
            function_text = ". ".join(sentence.strip().rstrip(".") for sentence in sentences if sentence).strip()
            if function_text:
                lines.append(function_text + ".")
        lines.append(
            f"ChEMBL target ID: {tc.chembl_id}. "
            f"UniProt accession: {tc.uniprot_id}. "
            f"{tc.known_inhibitors} known inhibitors identified in ChEMBL."
        )
        lines.append(
            f"Druggability score: {tc.druggability_score:.2f}/1.0. "
            f"Primary receptor structure used for docking: {tc.pdb_id}."
        )
        if tc.receptor_pdb_path and "tmp" in tc.receptor_pdb_path:
            lines.append("Note: Receptor structure was downloaded dynamically from RCSB for this run.")
        return " ".join(lines)

    # FIXED
    @staticmethod
    def _classification_badge(target_context: TargetContext) -> Table:
        classified = (target_context.target_class or "").lower() not in {"", "unknown", "other"}
        label = (
            f"Classification: {str(target_context.target_class).replace('_', ' ').title()}"
            if classified
            else "Classification: Not determined"
        )
        background = colors.HexColor("#dcfce7") if classified else colors.HexColor("#fef3c7")
        text_color = colors.HexColor("#166534") if classified else colors.HexColor("#b45309")
        table = Table([[label]], colWidths=[2.4 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), background),
                    ("TEXTCOLOR", (0, 0), (-1, -1), text_color),
                    ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                    ("BOX", (0, 0), (-1, -1), 0.5, text_color),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )
        return table

    # FIXED
    @staticmethod
    def build_confidence_assessment(
        target_context: TargetContext,
        docking_meta: dict,
        molecules: list,
        optimization_result: dict,
    ) -> dict:
        score_points = 0
        max_points = 0
        flags = []

        max_points += 3
        if docking_meta.get("receptor_prepared"):
            score_points += 2
        else:
            flags.append("Receptor not prepared - docking scores may be 20-30% less reliable")
        if docking_meta.get("binding_site_known"):
            score_points += 1
        else:
            flags.append("Binding site coordinates estimated - active site may be missed")

        max_points += 3
        best_score = min(
            (molecule.docking_score for molecule in molecules if molecule.docking_score is not None),
            default=0,
        )
        if best_score < -8:
            score_points += 3
        elif best_score < -7:
            score_points += 2
            flags.append("Docking scores moderate (< -7) - promising but not strong evidence")
        elif best_score < -6:
            score_points += 1
            flags.append("Docking scores weak (< -6) - experimental validation especially important")
        else:
            flags.append("Docking scores very weak - binding unlikely to be significant")

        max_points += 2
        if target_context.target_class not in ("unknown", "other"):
            score_points += 2
        else:
            flags.append("Target class not identified - molecule profiles are generic")

        max_points += 2
        if optimization_result and optimization_result.get("changes"):
            score_points += 2
        else:
            flags.append("No optimization performed - compounds are unrefined")

        model_sources = sorted(
            {
                str((molecule.admet_scores or {}).get("model_source")).strip()
                for molecule in molecules
                if (molecule.admet_scores or {}).get("model_source")
            }
        )
        if model_sources:
            flags.append(
                "ADMET values are ML predictions, not experimental measurements"
            )
        else:
            flags.append("ADMET provenance was not recorded clearly - treat values as predictive estimates")

        confidence_pct = int((score_points / max_points) * 100) if max_points else 0

        if confidence_pct >= 75:
            confidence_label = "HIGH - suitable for experimental follow-up"
        elif confidence_pct >= 50:
            confidence_label = "MODERATE - results are directionally useful"
        else:
            confidence_label = "LOW - treat as hypothesis generation only"

        return {
            "score": confidence_pct,
            "label": confidence_label,
            "flags": flags,
        }

    # FIXED
    @staticmethod
    def _confidence_bar(score: int) -> Drawing:
        width = 4.6 * inch
        height = 0.28 * inch
        drawing = Drawing(width, height + 12)
        drawing.add(Rect(0, 6, width, height, fillColor=colors.HexColor("#e5e7eb"), strokeColor=colors.HexColor("#cbd5e1")))
        fill_color = (
            colors.HexColor("#16a34a")
            if score >= 75
            else colors.HexColor("#d97706")
            if score >= 50
            else colors.HexColor("#dc2626")
        )
        drawing.add(Rect(0, 6, width * max(0, min(score, 100)) / 100.0, height, fillColor=fill_color, strokeColor=fill_color))
        drawing.add(String(width + 6, 7, f"{score}%", fontName="Helvetica-Bold", fontSize=9, fillColor=colors.HexColor("#0f172a")))
        return drawing

    @staticmethod
    def _coerce_known_inhibitors(value: Any) -> int:
        if isinstance(value, bool):
            return int(value)
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, dict):
            for key in ("count", "total", "known_inhibitors"):
                nested = value.get(key)
                if isinstance(nested, (int, float)):
                    return int(nested)
        return 0

    @staticmethod
    def _coerce_target_context(target: Any) -> TargetContext:
        if isinstance(target, TargetContext):
            return target

        protein_name = getattr(target, "protein_name", None) or getattr(target, "name", "") or ""
        gene_symbol = getattr(target, "gene_symbol", None) or protein_name
        pdb_id = getattr(target, "pdb_id", None) or ""
        receptor_pdb_path = getattr(target, "receptor_pdb_path", None)
        return TargetContext(
            target_id=str(getattr(target, "target_id", None) or getattr(target, "id")),
            gene_symbol=str(gene_symbol),
            protein_name=str(protein_name),
            disease=str(getattr(target, "disease", None) or ""),
            uniprot_id=str(getattr(target, "uniprot_id", None) or ""),
            chembl_id=str(getattr(target, "chembl_id", None) or ""),
            pdb_id=str(pdb_id),
            function=str(getattr(target, "function", None) or ""),
            known_inhibitors=ReportService._coerce_known_inhibitors(getattr(target, "known_inhibitors", None)),
            druggability_score=float(getattr(target, "druggability_score", None) or 0.0),
            target_class=str(getattr(target, "target_class", None) or "unknown"),
            receptor_pdb_path=str(receptor_pdb_path) if receptor_pdb_path else None,
            docking_center=getattr(target, "docking_center", None),
            docking_box_size=getattr(target, "docking_box_size", None),
        )

    @staticmethod
    def _report_target(target: Any) -> Any:
        target_context = ReportService._coerce_target_context(target)
        return SimpleNamespace(
            id=target_context.target_id,
            name=target_context.protein_name,
            gene_symbol=target_context.gene_symbol,
            disease=target_context.disease or "N/A",
            uniprot_id=target_context.uniprot_id or "N/A",
            chembl_id=target_context.chembl_id or "N/A",
            known_inhibitors=target_context.known_inhibitors,
            structure_count=1 if target_context.pdb_id else 0,
            pdb_id=target_context.pdb_id or "N/A",
            function=target_context.function,
            druggability_score=target_context.druggability_score,
            druggability_breakdown={},
            gemini_source="target_context",
            target_class=target_context.target_class,
            receptor_pdb_path=target_context.receptor_pdb_path,
        )

    @staticmethod
    def _methods_confidence_table(target_context: TargetContext, molecules: List[Any]) -> Table:
        docking_is_mock = any(
            bool(((molecule.admet_scores or {}).get("_docking") or {}).get("is_mock", False))
            for molecule in molecules
        )
        strict_lipinski_count = sum(
            1 for molecule in molecules if bool((molecule.admet_scores or {}).get("strict_lipinski_pass", False))
        )
        relaxed_lipinski_count = sum(1 for molecule in molecules if bool(getattr(molecule, "lipinski_pass", False)))
        rows = [
            ["Signal", "Value"],
            ["Docking mode", "Mock / estimated" if docking_is_mock else "Real receptor docking"],
            ["Biological text source", "Structured target context only"],
            ["ADMET source", "ML predictions / in silico models"],
            ["Strict Lipinski pass", f"{strict_lipinski_count}/{len(molecules)}"],
            ["Relaxed Lipinski pass", f"{relaxed_lipinski_count}/{len(molecules)}"],
            ["Target class", target_context.target_class if target_context.target_class not in {"unknown", "other"} else "Not determined"],
        ]
        table = Table(rows, colWidths=[2.3 * inch, 3.7 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )
        return table

    @staticmethod
    def _molecule_image(smiles: str) -> io.BytesIO | None:
        if not RDKIT_AVAILABLE:
            return None

        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None

        image = Draw.MolToImage(mol, size=(300, 220))
        buffer = io.BytesIO()
        image.save(buffer, format="PNG")
        buffer.seek(0)
        return buffer

    @staticmethod
    def _admet_table(admet_scores: Dict[str, Any]) -> Table:
        rows = [
            ["Property", "Value", "Traffic"],
            ["BBBP", ReportService._format_value(admet_scores.get("bbbp_score", "N/A")), admet_scores.get("bbbp_traffic", "unknown")],
            [
                "Hepatotoxicity",
                ReportService._format_value(admet_scores.get("hepatotoxicity_score", "N/A")),
                admet_scores.get("hepatotoxicity_traffic", "unknown"),
            ],
            ["hERG", "risk" if admet_scores.get("herg_risk") else "no risk", "red" if admet_scores.get("herg_risk") else "green"],
            [
                "Bioavailability",
                ReportService._format_value(admet_scores.get("bioavailability_score", "N/A")),
                admet_scores.get("bioavailability_traffic", "unknown"),
            ],
            ["Solubility", ReportService._format_value(admet_scores.get("solubility_score", "N/A")), admet_scores.get("solubility_traffic", "unknown")],
            ["Clearance", ReportService._format_value(admet_scores.get("clearance_score", "N/A")), admet_scores.get("clearance_traffic", "unknown")],
            ["CYP3A4", ReportService._format_value(admet_scores.get("cyp3a4_liability", "N/A")), admet_scores.get("cyp3a4_traffic", "unknown")],
        ]
        table = Table(rows, colWidths=[1.8 * inch, 1.4 * inch, 1.2 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )
        for row_index in range(1, len(rows)):
            traffic = str(rows[row_index][2]).lower()
            table.setStyle(
                TableStyle(
                    [
                        ("TEXTCOLOR", (2, row_index), (2, row_index), ReportService._traffic_color(traffic)),
                        ("FONTNAME", (2, row_index), (2, row_index), "Helvetica-Bold"),
                    ]
                )
            )
        return table

    @staticmethod
    def _target_summary_table(target: Any) -> Table:
        gene = getattr(target, "gene_symbol", None) or getattr(target, "gene", None) or target.name
        disease = getattr(target, "disease", None) or "N/A"
        known_inhibitors = getattr(target, "known_inhibitors", None)
        chembl_id = getattr(target, "chembl_id", None) or "N/A"

        rows = [
            ["UniProt ID", target.uniprot_id or "N/A"],
            ["Gene", gene or "N/A"],
            ["Disease", disease],
            ["Known Inhibitors", str(known_inhibitors) if known_inhibitors is not None else "N/A"],
            ["ChEMBL ID", chembl_id],
            ["Target Class", getattr(target, "target_class", None) if getattr(target, "target_class", None) not in {"unknown", "other", None, ""} else "Not determined"],
            ["PDB Structures", str(getattr(target, "structure_count", "N/A") or "N/A")],
            ["Top PDB ID", getattr(target, "pdb_id", None) or "N/A"],
        ]
        table = Table(rows, colWidths=[1.8 * inch, 4.5 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        return table

    @staticmethod
    def _overview_metrics_table(target: Any, molecules: List[Any]) -> Table:
        best_docking = next((molecule.docking_score for molecule in molecules if molecule.docking_score is not None), None)
        optimized_count = sum(1 for molecule in molecules if getattr(molecule, "is_optimized", False))
        lipinski_rate = (
            round(sum(1 for molecule in molecules if molecule.lipinski_pass) / len(molecules) * 100)
            if molecules
            else 0
        )
        rows = [
            ["Overview Metric", "Value"],
            ["Generated Compounds Reviewed", str(len(molecules))],
            ["Lipinski Pass Rate", f"{lipinski_rate}%"],
            ["Best Docking Score", f"{best_docking:.2f} kcal/mol" if best_docking is not None else "N/A"],
            ["Optimized Leads", str(optimized_count)],
            ["Druggability Score", f"{round(getattr(target, 'druggability_score', 0.0) or 0.0, 2)}/1.0"],
        ]
        table = Table(rows, colWidths=[2.6 * inch, 2.4 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )
        return table

    @staticmethod
    def _traffic_legend_table() -> Table:
        styles = ReportService._styles()
        cell_style = styles["MolTable"]
        header_style = ParagraphStyle(
            "MolTableHeader",
            parent=cell_style,
            fontName="Helvetica-Bold",
            textColor=colors.HexColor("#0f172a"),
        )

        def cell(text: str, *, header: bool = False) -> Paragraph:
            safe = html.escape(text)
            return Paragraph(safe, header_style if header else cell_style)

        rows = [
            [cell("Domain", header=True), cell("Green", header=True), cell("Yellow", header=True), cell("Red", header=True)],
            [cell("BBBP / Bioavailability / Solubility / Clearance"), cell("> 0.70"), cell("0.40 to 0.70"), cell("< 0.40")],
            [cell("Hepatotoxicity / CYP3A4 Liability"), cell("< 0.30"), cell("0.30 to 0.60"), cell("> 0.60")],
            [cell("hERG"), cell("No predicted risk"), cell("Borderline; review confidence"), cell("Predicted risk present")],
            [cell("SAS Score"), cell("<= 3.00"), cell("3.01 to 6.00"), cell("> 6.00")],
            [cell("Docking Score"), cell("<= -7.0 kcal/mol"), cell("-7.0 to -5.0 kcal/mol"), cell("> -5.0 kcal/mol")],
        ]
        table = Table(rows, colWidths=[2.8 * inch, 1.1 * inch, 1.25 * inch, 1.1 * inch], repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dbeafe")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("BACKGROUND", (1, 1), (1, -1), colors.HexColor("#ecfdf5")),
                    ("BACKGROUND", (2, 1), (2, -1), colors.HexColor("#fef9c3")),
                    ("BACKGROUND", (3, 1), (3, -1), colors.HexColor("#fee2e2")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )
        return table

    @staticmethod
    def _molecule_identity_table(index: int, molecule: Any) -> Table:
        rows = [
            ["Assigned Report Name", ReportService._molecule_report_name(index, molecule)],
            ["Internal Rank", f"Lead Candidate {index}"],
            ["SMILES", molecule.smiles],
            ["Lipinski Status", "Pass" if molecule.lipinski_pass else "Fail"],
            ["SAS Score", ReportService._format_value(molecule.sas_score)],
            ["Docking Score", f"{ReportService._format_value(molecule.docking_score)} kcal/mol" if molecule.docking_score is not None else "N/A"],
        ]
        table = Table(rows, colWidths=[2.0 * inch, 4.3 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f8fafc")),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        return table

    @staticmethod
    def _target_label(target: Any) -> str:
        disease = getattr(target, "disease", None)
        return f"{target.name} in {disease}" if disease and disease != "N/A" else str(getattr(target, "name", "this target"))

    @staticmethod
    def _admet_interpretation_snippets(admet: Dict[str, Any]) -> List[str]:
        snippets: List[str] = []

        if admet.get("hepatotoxicity_traffic") == "red":
            snippets.append("hepatotoxicity is the main development liability")
        elif admet.get("hepatotoxicity_traffic") == "green":
            snippets.append("hepatotoxicity risk appears comparatively manageable")

        if admet.get("herg_risk") is True:
            snippets.append("predicted hERG liability would need explicit follow-up")
        elif admet.get("herg_risk") is False:
            snippets.append("no major hERG warning is currently predicted")

        if admet.get("bioavailability_traffic") == "green":
            snippets.append("oral exposure potential is directionally supportive")
        elif admet.get("bioavailability_traffic") == "red":
            snippets.append("bioavailability may limit progression without chemistry refinement")

        if admet.get("cyp3a4_traffic") == "red":
            snippets.append("CYP3A4 liability suggests possible metabolism or interaction concerns")

        if admet.get("solubility_traffic") == "red":
            snippets.append("solubility could become a formulation and assay constraint")

        if not snippets:
            snippets.append("the ADMET profile is mixed and should be interpreted as an early triage signal rather than a decision-ready profile")

        return snippets[:3]

    @staticmethod
    def _compound_interpretation(target: Any, molecule: Any, index: int) -> str:
        admet = molecule.admet_scores or {}
        descriptors = ReportService._molecule_descriptors(molecule)
        name = ReportService._molecule_report_name(index, molecule)
        target_label = ReportService._target_label(target)
        admet_summary = "; ".join(ReportService._admet_interpretation_snippets(admet))
        docking_note = (
            f"The docking score for {name} is {molecule.docking_score:.2f} kcal/mol, which is interpreted as "
            + ("strong" if molecule.docking_score is not None and molecule.docking_score <= -7 else "moderate" if molecule.docking_score is not None and molecule.docking_score <= -5 else "weak or uncertain")
            + f" predicted receptor engagement for {target_label} under the current workflow."
            if molecule.docking_score is not None
            else f"No docking score was available for {name}; binding interpretation against {target_label} should therefore remain provisional."
        )
        return (
            f"{name} is presented as Lead Candidate {index} for {target_label}. The compound shows a synthetic accessibility "
            f"score of {ReportService._format_value(molecule.sas_score)}, indicating "
            f"{'relatively straightforward' if molecule.sas_score is not None and molecule.sas_score <= 3 else 'moderate' if molecule.sas_score is not None and molecule.sas_score <= 6 else 'challenging'} "
            f"expected tractability for synthesis. The recorded molecular weight is {ReportService._format_value(descriptors['molecular_weight'])} Da and the LogP estimate is "
            f"{ReportService._format_value(descriptors['logp'])}, which should be interpreted together with Lipinski status "
            f"({'pass' if molecule.lipinski_pass else 'fail'}) when considering oral small-molecule suitability.\n\n"
            f"{docking_note} From a developability perspective, {admet_summary}. These observations should be read as prioritization guidance for medicinal chemistry around "
            f"{target_label}, not as a clinical conclusion."
        )

    @staticmethod
    def _molecule_rows(target: Any, molecules: List[Any]) -> List[Any]:
        styles = ReportService._styles()
        story: List[Any] = []

        for index, molecule in enumerate(molecules, start=1):
            story.append(PageBreak())
            story.append(Paragraph(f"Compound Review: {ReportService._molecule_report_name(index, molecule)}", styles["MolHeading"]))
            story.append(Paragraph(f"Lead Candidate {index}", styles["MolSubtitle"]))
            story.append(ReportService._molecule_identity_table(index, molecule))
            story.append(Spacer(1, 0.15 * inch))

            image_buffer = ReportService._molecule_image(molecule.smiles)
            if image_buffer is not None:
                story.append(Image(image_buffer, width=3.0 * inch, height=2.2 * inch))
                story.append(Spacer(1, 0.15 * inch))
            else:
                story.append(Paragraph("2D structure image unavailable in this environment.", styles["MolSmall"]))

            story.append(Paragraph("ADMET Risk Table", styles["MolHeading"]))
            story.append(ReportService._admet_table(molecule.admet_scores or {}))
            docking_meta = (molecule.admet_scores or {}).get("_docking", {})
            model_source = (molecule.admet_scores or {}).get("model_source")
            if model_source:
                story.append(Paragraph(f"ADMET Source: {model_source}", styles["MolSmall"]))
            if docking_meta.get("is_mock"):
                story.append(
                    Paragraph(
                        "* Docking scores estimated via RDKit descriptor model. AutoDock Vina not available in this environment.",
                        styles["MolSmall"],
                    )
                )
            story.append(Spacer(1, 0.15 * inch))
            story.append(Paragraph("Professional Interpretation", styles["MolHeading"]))
            story.append(Paragraph(ReportService._compound_interpretation(target, molecule, index).replace("\n", "<br/><br/>"), styles["MolBody"]))
            story.append(Spacer(1, 0.25 * inch))

        return story

    @staticmethod
    def _provenance_table(target: Any, molecules: List[Any]) -> Table:
        docking_modes = []
        admet_sources = []
        for molecule in molecules:
            admet = molecule.admet_scores or {}
            docking_meta = admet.get("_docking", {})
            if isinstance(docking_meta, dict) and docking_meta.get("method"):
                method = str(docking_meta.get("method"))
                if method == "rdkit_fallback" or docking_meta.get("is_mock"):
                    docking_modes.append("rdkit_fallback")
                elif method == "vina":
                    docking_modes.append("vina")
                elif method == "legacy_stored_score":
                    docking_modes.append("legacy_stored_score")
                elif method == "not_run":
                    docking_modes.append("not_run")
            if admet.get("model_source"):
                admet_sources.append(admet["model_source"])

        rows = [
            ["Signal", "Source"],
            ["Target extraction", getattr(target, "gemini_source", None) or "unknown"],
            ["Druggability", "rule_based_breakdown"],
            ["ADMET", ", ".join(sorted(set(admet_sources))) if admet_sources else "unknown"],
            ["Docking", ", ".join(sorted(set(docking_modes))) if docking_modes else "unknown"],
        ]
        table = Table(rows, colWidths=[2.0 * inch, 4.0 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ]
            )
        )
        return table

    @staticmethod
    def _clinical_interpretation_text(target: Any, molecules: List[Any]) -> str:
        best = next((m for m in molecules if m.docking_score is not None), None)
        optimized = next((m for m in molecules if getattr(m, "is_optimized", False)), None)
        best_name = ReportService._molecule_report_name(molecules.index(best) + 1, best) if best else "the top-ranked compound"
        optimized_name = ReportService._molecule_report_name(molecules.index(optimized) + 1, optimized) if optimized else "no dedicated optimized lead"
        target_label = ReportService._target_label(target)
        target_function = getattr(target, "function", None) or "No mechanism summary was available from the enrichment step."
        return (
            f"This report should be interpreted as an early-stage computational assessment for {html.escape(target_label)}. "
            f"The target overview, mechanistic context, and compound triage are intended to support medicinal chemistry prioritization rather than make a therapeutic claim. "
            f"In the current enrichment record, the target function is summarized as follows: {html.escape(target_function)}\n\n"
            f"The most relevant immediate output is the relative ranking between compounds, especially the balance between docking affinity, synthetic accessibility, and ADMET liabilities.\n\n"
            f"Among the reviewed compounds, {best_name} represents the strongest currently recorded docking candidate in this batch for {html.escape(target_label)}. A stronger docking score can suggest improved geometric or energetic complementarity to the receptor model, "
            f"but the value should still be interpreted cautiously because docking remains highly dependent on receptor preparation, protonation state, and binding-site assumptions. "
            f"For that reason, any compound prioritized from this report should undergo confirmatory redocking, visual pose inspection, and if possible orthogonal scoring before wet-lab commitment.\n\n"
            f"The traffic-light system is designed for quick professional triage. Green values identify properties that are presently favorable within the internal thresholds, yellow values indicate an acceptable but cautionary range that may need scaffold tuning, "
            f"and red values flag liabilities likely to limit progression unless compensated by exceptional potency or tractable chemistry. In practical terms, a compound with green docking but red hepatotoxicity or CYP3A4 liability should not be considered a clean lead; "
            f"it is better described as an interesting scaffold requiring targeted remediation.\n\n"
            f"The presence of {optimized_name} in the set indicates that the workflow attempted lead refinement after initial ranking. That optimization step should be viewed as hypothesis generation: it proposes a direction for chemical improvement, but not a final clinical candidate. "
            f"The recommended next actions after this report are compound identity review, analog expansion around the strongest scaffold, explicit ADMET confirmation with higher-fidelity models or assays, and receptor-specific medicinal chemistry discussion focused on potency-selectivity-toxicity tradeoffs."
        )

    @staticmethod
    def _build_pdf(target_context: TargetContext, target: Any, molecules: List[Any], output: Any) -> None:
        styles = ReportService._styles()
        summary = ReportService.build_target_description(target_context)
        # FIXED
        docking_meta = next(
            (
                (molecule.admet_scores or {}).get("_docking", {})
                for molecule in molecules
                if isinstance((molecule.admet_scores or {}).get("_docking", {}), dict)
            ),
            {},
        )
        # FIXED
        optimized_molecule = next((molecule for molecule in molecules if getattr(molecule, "is_optimized", False)), None)
        # FIXED
        optimization_result = {
            "changes": list(getattr(optimized_molecule, "optimization_changes", []) or [])
        } if optimized_molecule is not None else {}
        # FIXED
        confidence = ReportService.build_confidence_assessment(target_context, docking_meta, molecules, optimization_result)

        doc = SimpleDocTemplate(output, pagesize=A4, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        story: List[Any] = []

        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        story.extend(
            [
                Paragraph("MolGenix Computational Lead Evaluation Report", styles["MolTitle"]),
                Paragraph(f"Target under review: {target.name}", styles["MolSubtitle"]),
                ReportService._classification_badge(target_context),
                Spacer(1, 0.08 * inch),
                Paragraph(f"Generated: {generated_at}", styles["MolBody"]),
                Paragraph("Executive Overview", styles["MolHeading"]),
                Paragraph(
                    "This document summarizes target context, compound ranking, ADMET interpretation, and docking-based lead review in a format intended for medicinal chemistry and translational discussion.",
                    styles["MolBody"],
                ),
                ReportService._overview_metrics_table(target, molecules),
                Spacer(1, 0.18 * inch),
                Paragraph("Target Summary", styles["MolHeading"]),
                ReportService._target_summary_table(target),
                Spacer(1, 0.2 * inch),
                Paragraph(summary.replace("\n", "<br/>"), styles["MolBody"]),
                Spacer(1, 0.2 * inch),
                Paragraph("Computational Methods & Confidence", styles["MolHeading"]),
                ReportService._methods_confidence_table(target_context, molecules),
                Spacer(1, 0.2 * inch),
                # FIXED
                Paragraph("Computational Confidence", styles["MolHeading"]),
                # FIXED
                Paragraph(confidence["label"], styles["MolBody"]),
                # FIXED
                ReportService._confidence_bar(confidence["score"]),
                Spacer(1, 0.12 * inch),
                Paragraph("Evidence and Model Sources", styles["MolHeading"]),
                ReportService._provenance_table(target, molecules),
                Spacer(1, 0.2 * inch),
                KeepTogether(
                    [
                        Paragraph("Interpretation Matrix", styles["MolHeading"]),
                        Paragraph(
                            "The following ranges define how the green, yellow, and red classifications are assigned within the report.",
                            styles["MolBody"],
                        ),
                        ReportService._traffic_legend_table(),
                    ]
                ),
                Spacer(1, 0.18 * inch),
                # FIXED
                Paragraph("Confidence Flags", styles["MolHeading"]),
            ]
        )

        # FIXED
        for flag in confidence["flags"]:
            story.append(Paragraph(f"&bull; {html.escape(flag)}", styles["MolBody"]))

        # FIXED
        story.append(Spacer(1, 0.15 * inch))
        # FIXED
        story.append(Paragraph(STANDARD_DISCLAIMER, styles["MolSmall"]))

        story.extend(ReportService._molecule_rows(target, molecules))
        story.append(PageBreak())
        story.append(Paragraph("Clinical and Medicinal Chemistry Interpretation", styles["MolHeading"]))
        story.append(Paragraph(ReportService._clinical_interpretation_text(target, molecules).replace("\n", "<br/><br/>"), styles["MolBody"]))
        # FIXED
        story.append(Spacer(1, 0.18 * inch))
        # FIXED
        story.append(Paragraph(STANDARD_DISCLAIMER, styles["MolSmall"]))

        doc.build(story)

    @staticmethod
    async def generate_report(
        target_context: TargetContext,
        molecules: List[Any],
        db: Any,
    ) -> Dict[str, Any]:
        """Generate a PDF report for a target context and molecule set."""
        from app.models.report import Report
        from app.models.target import Target

        target = db.query(Target).filter(Target.id == target_context.target_id).first()
        if not target:
            raise ValueError("Target not found")

        if not molecules:
            raise ValueError("molecules required for report generation")

        logger.info(
            "Generating report for target %s with %s molecules",
            target_context.target_id,
            len(molecules),
        )

        ordered_molecules = sorted(
            molecules,
            key=lambda molecule: (
                molecule.docking_score is None,
                molecule.docking_score if molecule.docking_score is not None else float("inf"),
            ),
        )[:5]
        report_target = ReportService._report_target(target_context)
        ordered_molecules = await ReportService._ensure_molecule_annotations(report_target, ordered_molecules, db)
        ReportService.REPORT_STORAGE_DIR.mkdir(parents=True, exist_ok=True)
        report = Report(
            target_id=target.id,
            molecule_ids=[str(molecule.id) for molecule in ordered_molecules],
            pdf_path="",
            file_size_bytes=0,
        )
        db.add(report)
        db.commit()
        db.refresh(report)

        buffer = io.BytesIO()
        ReportService._build_pdf(target_context, report_target, ordered_molecules, buffer)
        pdf_bytes = buffer.getvalue()
        report_path = ReportService.REPORT_STORAGE_DIR / f"{report.id}.pdf"
        report_path.write_bytes(pdf_bytes)
        report.pdf_path = str(report_path)
        report.file_size_bytes = len(pdf_bytes)
        db.add(report)
        db.commit()
        db.refresh(report)

        return {
            "report_id": str(report.id),
            "pdf_url": f"/api/reports/{report.id}/download",
        }

    @staticmethod
    async def generate_report_for_target(
        target_id: str,
        db: Any,
        target_context: Any | None = None,
        molecule_ids: List[str] | None = None,
    ) -> Dict[str, Any]:
        """Backward-compatible wrapper that assembles report inputs from persisted rows."""
        from app.models.molecule import Molecule
        from app.models.target import Target

        target = db.query(Target).filter(Target.id == target_id).first()
        if not target:
            raise ValueError("Target not found")

        if not molecule_ids:
            raise ValueError("molecule_ids required for report generation")

        logger.info(
            "Generating report for target %s with %s molecule IDs: %s",
            target_id,
            len(molecule_ids),
            molecule_ids,
        )

        molecule_query = db.query(Molecule).filter(Molecule.target_id == target.id)
        molecule_uuids = [UUID(str(molecule_id)) for molecule_id in molecule_ids]
        molecule_query = molecule_query.filter(Molecule.id.in_(molecule_uuids))

        molecules = molecule_query.order_by(Molecule.docking_score.asc().nullslast(), Molecule.created_at.desc()).limit(5).all()
        if len(molecules) < 1:
            raise ValueError("No molecules found for target")

        context = ReportService._coerce_target_context(target_context or target)
        return await ReportService.generate_report(context, molecules, db)

    @staticmethod
    async def generate_report_bytes(
        target_id: str,
        db: Any,
        target_context: Any | None = None,
        molecule_ids: List[str] | None = None,
    ) -> bytes:
        """Generate a report PDF in memory without persisting it to disk."""
        from app.models.molecule import Molecule
        from app.models.target import Target

        target = db.query(Target).filter(Target.id == target_id).first()
        if not target:
            raise ValueError("Target not found")

        if not molecule_ids:
            raise ValueError("molecule_ids required for report generation")

        molecule_query = db.query(Molecule).filter(Molecule.target_id == target.id)
        molecule_uuids = [UUID(str(molecule_id)) for molecule_id in molecule_ids]
        molecule_query = molecule_query.filter(Molecule.id.in_(molecule_uuids))
        molecules = molecule_query.order_by(Molecule.docking_score.asc().nullslast(), Molecule.created_at.desc()).limit(5).all()
        if len(molecules) < 1:
            raise ValueError("No molecules found for target")

        report_target = ReportService._report_target(target_context or target)
        molecules = await ReportService._ensure_molecule_annotations(report_target, molecules, db)
        buffer = io.BytesIO()
        ReportService._build_pdf(ReportService._coerce_target_context(target_context or target), report_target, molecules, buffer)
        return buffer.getvalue()
